### ISSUE TITLE
`declaration-block-no-shorthand-property-overrides` preventing multiple font related properties

### ISSUE THREAD

**Issue by crowjm** [DockYard/stylelint-config-narwin#3]
Originally when there were multiple font related properties, stylelint would throw an error: `Unexpected shorthand "font" after "font-size"   declaration-block-no-shorthand-property-overrides`

This error was being thrown because of the following CSS:
```
font-size: 100%;
font: inherit;
```

After looking into some of [the options for that rule](https://stylelint.io/user-guide/rules/declaration-block-no-duplicate-properties/), Cory & I decided to swap the order of the CSS so that the shorthand declaration was first followed by more specific declarations. (This also makes more sense to me because the code starts general and gets more specific and can override items in the shorthand.)

```
font: inherit;
font-size: 100%;
```

After doing this, the linter throws no errors. Maybe the solution to this isn't in the `declaration-block-no-shorthand-property-overrides` part of the linter, but an addition to the linter where an error is thrown if shorthand properties are listed after more specific properties?

**Comment by eshtadc** [comment]
So it looks to me that we wouldn't need to change anything in order to allow the solution you implemented in changing the order of the CSS.
https://stylelint.io/user-guide/rules/declaration-block-no-shorthand-property-overrides/#declaration-block-no-shorthand-property-overrides
The docs show a similar approach in their first example of patterns that are not considered violations.
